apiVersion: v1
kind: Namespace
metadata:
  name: kata2

---
# Ingress - Routes external traffic to services
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kata2-ingress
  namespace: kata2
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /auth
        pathType: Prefix
        backend:
          service:
            name: keycloak-service
            port:
              number: 8080 # This is what the keycloak service is exposing