curl -X POST 'http://127.0.0.1:54434/auth/realms/kata2realm/protocol/openid-connect/token' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d 'client_id=kata2' \
  -d 'username=alice' \
  -d 'password=alice123' \
  -d 'grant_type=password'