PUT http://127.0.0.1:54434/auth/admin/realms/kata2realm/users/332bcf99-ef9d-489f-9505-463f114f9d87/reset-password
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJFdVNWcGNSeUdrUVdtMkwydURsc3NWQ2RsTUk1U3NXbGlqOGFvSUY1SGhRIn0.eyJleHAiOjE3NzcwNTMwNTEsImlhdCI6MTc3NzA1Mjk5MSwianRpIjoib25sdHJvOmI4M2QxYWRkLTc1ZDktN2JiNi1hM2JjLWJjOWIyZmY3YmUxMyIsImlzcyI6Imh0dHA6Ly8xMjcuMC4wLjE6NTQ0MzQvYXV0aC9yZWFsbXMvbWFzdGVyIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiYWRtaW4tY2xpIiwic2lkIjoieXBSdzZnS2p6cTFfTXNPaEpuaXFpdi1ZIiwic2NvcGUiOiJlbWFpbCBwcm9maWxlIn0.ISlafO6ppZy-gyu1hKdH67C0iHF7zalDMX853d_vBaz74DtiKTB3Hq5K9ouuQKgyGJocqI7vZzg7AqI74-KkNLDhHoNGVuFv-LkwRigNhdZP0vzyRDkp9INq7I4FVvgQv3U_lJvxy71M1roEF6aPohlpBn9eup3NMNrG-NbJHTfU1sBrNDlu_vsWqqvW3dpmX_njndTIKDrtRvI538EnPUBjbF-ePYfU5HFAKGntlzE1YES7cOflFy3577LsCDbCYHyb3_UTo1v9v94Ox4XAuJAfruabBD7Ou1wqwi_bCWzSFicuNHlNJl6NSRtxogTiLdLb3hgOW_mJ7XMpTGC_DQ
Content-Type: application/json

{
  "type": "password",
  "value": "alice123",
  "temporary": false
}