PUT http://127.0.0.1:54434/auth/admin/realms/kata2realm/users/alice/reset-password
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJFdVNWcGNSeUdrUVdtMkwydURsc3NWQ2RsTUk1U3NXbGlqOGFvSUY1SGhRIn0.eyJleHAiOjE3NzcwNTI5MzksImlhdCI6MTc3NzA1Mjg3OSwianRpIjoib25sdHJvOmJmMTUxNzY2LWEyMDUtMmYxNi02NTQzLWQyNzA2YWMzYjg3MiIsImlzcyI6Imh0dHA6Ly8xMjcuMC4wLjE6NTQ0MzQvYXV0aC9yZWFsbXMvbWFzdGVyIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiYWRtaW4tY2xpIiwic2lkIjoic1Y5TlB2NlpPSHB0S1hMbHZNbXJFRFhzIiwic2NvcGUiOiJlbWFpbCBwcm9maWxlIn0.JH3OuH5QqW3WbNFO2MaXYMnChprCb7luAmSXvabRAQXvBO21eQP28fbnmTXsaF1uubwoZ2Fp_NiXMnL47oYVjxZE64K0bwRjlyGjgXWUrZBC68qoVFNMAfhI_0MLnxL5RkokbiFK5bs6NJTNQgOnmm64EDsugeGK1RDFGIhCrgHqpzJ-rPXeSA2UqFTCa6JTs4sJNbqW9wxv33BlXJ3cpu78Yu1p7KhhX2igsTve2O_9zb1nzNg6VtavypPRG2kdbXwwCCW4i-bk_t609Uhck_PSlAWjTK31XhfHbLg8iSfCsAkzF9ozyYEcDGUydg5EHZQCvDfrgWwB0vlmuIA5sA
Content-Type: application/json

{
  "type": "password",
  "value": "alice123",
  "temporary": false
}